/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { JobApplication, TimelineEvent } from '../types';

const generateId = () => Math.random().toString(36).substring(2, 11);

// Helper to create date relative to current year
const relativeDate = (daysAgo: number) => {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString().split('T')[0];
};

export const MOCK_APPLICATIONS: JobApplication[] = [
  {
    id: 'stripe-001',
    company: 'Stripe',
    position: 'Senior Software Engineer (Billing)',
    status: 'Offer',
    location: 'San Francisco, CA',
    remote: 'Hybrid',
    salaryMin: 180000,
    salaryMax: 230000,
    salaryText: '$180,000 - $230,000 + Equity',
    source: 'LinkedIn',
    jobUrl: 'https://stripe.com/jobs',
    notes: 'Had final panel interviews last week. System design went extremely well, coding was smooth, behavioral was solid. Recruiter called with verbal offer!',
    appliedDate: relativeDate(32),
    lastUpdated: relativeDate(2),
    createdAt: relativeDate(32),
    timeline: [
      { id: 't1', applicationId: 'stripe-001', status: 'Applied', notes: 'Applied online via referral from Sarah.', createdAt: relativeDate(32) },
      { id: 't2', applicationId: 'stripe-001', status: 'Recruiter Screen', notes: 'Initial chat with recruiter. Discussed experience and expectations.', createdAt: relativeDate(25) },
      { id: 't3', applicationId: 'stripe-001', status: 'Assessment', notes: 'Take-home tech screen (Stripe API integration task).', createdAt: relativeDate(20) },
      { id: 't4', applicationId: 'stripe-001', status: 'Interview', notes: 'Technical phone interview on system design.', createdAt: relativeDate(12) },
      { id: 't5', applicationId: 'stripe-001', status: 'Final Interview', notes: 'Virtual onsite: 3 coding, 1 system design, 1 manager chat.', createdAt: relativeDate(6) },
      { id: 't6', applicationId: 'stripe-001', status: 'Offer', notes: 'Received formal written offer. Under negotiation.', createdAt: relativeDate(2) },
    ]
  },
  {
    id: 'google-001',
    company: 'Google',
    position: 'Staff Frontend Engineer (Cloud)',
    status: 'Interview',
    location: 'Mountain View, CA',
    remote: 'Hybrid',
    salaryMin: 210000,
    salaryMax: 275000,
    salaryText: '$210,000 - $275,000',
    source: 'Google Careers',
    jobUrl: 'https://careers.google.com',
    notes: 'Completed recruiter screening and initial technical screen. Scheduled for 5 rounds of virtual onsite interviews.',
    appliedDate: relativeDate(28),
    lastUpdated: relativeDate(4),
    createdAt: relativeDate(28),
    timeline: [
      { id: 't7', applicationId: 'google-001', status: 'Applied', notes: 'Applied via Google Careers site.', createdAt: relativeDate(28) },
      { id: 't8', applicationId: 'google-001', status: 'Recruiter Screen', notes: 'Recruiter reach-out to coordinate first phone screen.', createdAt: relativeDate(21) },
      { id: 't9', applicationId: 'google-001', status: 'Assessment', notes: 'Technical phone screen covering complex data structures.', createdAt: relativeDate(14) },
      { id: 't10', applicationId: 'google-001', status: 'Interview', notes: 'Onsite invitation confirmed. Preparing for behavioral and system design.', createdAt: relativeDate(4) },
    ]
  },
  {
    id: 'openai-001',
    company: 'OpenAI',
    position: 'Research Engineer (Alignment)',
    status: 'Assessment',
    location: 'San Francisco, CA',
    remote: 'Onsite',
    salaryMin: 240000,
    salaryMax: 350000,
    salaryText: '$240,000 - $350,000 + Large Equity',
    source: 'Twitter/X',
    jobUrl: 'https://openai.com/careers',
    notes: 'Working on a rigorous take-home machine learning alignment task due this Friday.',
    appliedDate: relativeDate(12),
    lastUpdated: relativeDate(11),
    createdAt: relativeDate(12),
    timeline: [
      { id: 't11', applicationId: 'openai-001', status: 'Applied', notes: 'Applied after seeing a posting by a team lead on X.', createdAt: relativeDate(12) },
      { id: 't12', applicationId: 'openai-001', status: 'Assessment', notes: 'Received machine learning assessment invitation.', createdAt: relativeDate(11) },
    ]
  },
  {
    id: 'spotify-001',
    company: 'Spotify',
    position: 'Senior Product Designer',
    status: 'Final Interview',
    location: 'New York, NY',
    remote: 'Remote',
    salaryMin: 160000,
    salaryMax: 210000,
    salaryText: '$160,000 - $210,000',
    source: 'LinkedIn',
    jobUrl: 'https://spotify.com/jobs',
    notes: 'Final portfolio presentation and app critique scheduled for tomorrow morning.',
    appliedDate: relativeDate(30),
    lastUpdated: relativeDate(3),
    createdAt: relativeDate(30),
    timeline: [
      { id: 't13', applicationId: 'spotify-001', status: 'Applied', notes: 'Applied via LinkedIn Easy Apply.', createdAt: relativeDate(30) },
      { id: 't14', applicationId: 'spotify-001', status: 'Recruiter Screen', notes: 'Recruiter call, very positive vibes. Highlighted work-from-anywhere policy.', createdAt: relativeDate(22) },
      { id: 't15', applicationId: 'spotify-001', status: 'Interview', notes: 'Technical deep-dive into portfolio cases with lead designer.', createdAt: relativeDate(15) },
      { id: 't16', applicationId: 'spotify-001', status: 'Final Interview', notes: 'Invited to final round. Prepping the slide deck.', createdAt: relativeDate(3) },
    ]
  },
  {
    id: 'microsoft-001',
    company: 'Microsoft',
    position: 'Software Engineer II (Azure Storage)',
    status: 'Accepted',
    location: 'Redmond, WA',
    remote: 'Hybrid',
    salaryMin: 145000,
    salaryMax: 185000,
    salaryText: '$155,000 Base + Bonus + Stock',
    source: 'Direct Sourcing',
    jobUrl: 'https://careers.microsoft.com',
    notes: 'ACCEPTED OFFER! Signed the paperwork, background check cleared, start date is set for next month. Stoked!',
    appliedDate: relativeDate(50),
    lastUpdated: relativeDate(15),
    createdAt: relativeDate(50),
    timeline: [
      { id: 't17', applicationId: 'microsoft-001', status: 'Applied', notes: 'Sourced by technical recruiter on LinkedIn.', createdAt: relativeDate(50) },
      { id: 't18', applicationId: 'microsoft-001', status: 'Recruiter Screen', notes: 'Recruiter phone screening.', createdAt: relativeDate(42) },
      { id: 't19', applicationId: 'microsoft-001', status: 'Interview', notes: 'First round technical screen (algorithms).', createdAt: relativeDate(35) },
      { id: 't20', applicationId: 'microsoft-001', status: 'Final Interview', notes: 'Full loop (4 sessions covering coding, system design, architecture).', createdAt: relativeDate(25) },
      { id: 't21', applicationId: 'microsoft-001', status: 'Offer', notes: 'Received official offer of $155k base + stock.', createdAt: relativeDate(20) },
      { id: 't22', applicationId: 'microsoft-001', status: 'Accepted', notes: 'Signed the offer letter. Adventure awaits!', createdAt: relativeDate(15) },
    ]
  },
  {
    id: 'hubspot-001',
    company: 'HubSpot',
    position: 'Full Stack Engineer (Growth)',
    status: 'Rejected',
    location: 'Boston, MA',
    remote: 'Remote',
    salaryMin: 130000,
    salaryMax: 170000,
    salaryText: '$140,000 + Benefits',
    source: 'Indeed',
    jobUrl: 'https://careers.hubspot.com',
    notes: 'Got standard rejection email after final round. Feedback was positive but they went with someone with more React 19 / Next.js experimental feature experience.',
    appliedDate: relativeDate(45),
    lastUpdated: relativeDate(18),
    createdAt: relativeDate(45),
    timeline: [
      { id: 't23', applicationId: 'hubspot-001', status: 'Applied', notes: 'Applied on HubSpot careers site.', createdAt: relativeDate(45) },
      { id: 't24', applicationId: 'hubspot-001', status: 'Recruiter Screen', notes: ' Recruiter chat. Excellent cultural alignment.', createdAt: relativeDate(38) },
      { id: 't25', applicationId: 'hubspot-001', status: 'Interview', notes: 'Pair programming session with senior engineer.', createdAt: relativeDate(28) },
      { id: 't26', applicationId: 'hubspot-001', status: 'Final Interview', notes: 'Manager + Team panel chat.', createdAt: relativeDate(22) },
      { id: 't27', applicationId: 'hubspot-001', status: 'Rejected', notes: 'Standard rejection email. Bummer, but great interview practice.', createdAt: relativeDate(18) },
    ]
  },
  {
    id: 'cloudflare-001',
    company: 'Cloudflare',
    position: 'Systems Engineer (Workers)',
    status: 'Recruiter Screen',
    location: 'Austin, TX',
    remote: 'Hybrid',
    salaryMin: 150000,
    salaryMax: 195000,
    salaryText: '$160,000 - $190,000',
    source: 'Hacker News',
    jobUrl: 'https://cloudflare.com/careers',
    notes: 'Recruiter reached out following a comment I left on Hacker News "Who is Hiring". Initial screen booked for next Tuesday.',
    appliedDate: relativeDate(5),
    lastUpdated: relativeDate(4),
    createdAt: relativeDate(5),
    timeline: [
      { id: 't28', applicationId: 'cloudflare-001', status: 'Applied', notes: 'Emailed manager from HN posting.', createdAt: relativeDate(5) },
      { id: 't29', applicationId: 'cloudflare-001', status: 'Recruiter Screen', notes: 'Recruiter scheduled first screening.', createdAt: relativeDate(4) },
    ]
  },
  {
    id: 'atlassian-001',
    company: 'Atlassian',
    position: 'Senior Frontend Developer (Jira)',
    status: 'Applied',
    location: 'Sydney, AU (Remote US)',
    remote: 'Remote',
    salaryMin: 155000,
    salaryMax: 190000,
    salaryText: '$155,000 - $190,000',
    source: 'LinkedIn',
    jobUrl: 'https://atlassian.com/careers',
    notes: 'Applied online. Jira is a massive tool, hoping my experience with rich text editors and dashboard performance gets me in the door.',
    appliedDate: relativeDate(6),
    lastUpdated: relativeDate(6),
    createdAt: relativeDate(6),
    timeline: [
      { id: 't30', applicationId: 'atlassian-001', status: 'Applied', notes: 'Applied through LinkedIn.', createdAt: relativeDate(6) },
    ]
  },
  {
    id: 'shopify-001',
    company: 'Shopify',
    position: 'Staff Developer (Core Platform)',
    status: 'Ghosted',
    location: 'Toronto, ON',
    remote: 'Remote',
    salaryMin: 170000,
    salaryMax: 220000,
    salaryText: '$180,000 - $210,000',
    source: 'LinkedIn',
    jobUrl: 'https://shopify.engineering',
    notes: 'Applied 6 weeks ago, had recruiter screen 4 weeks ago, but haven\'t heard back since. Followed up twice. Marking as ghosted.',
    appliedDate: relativeDate(42),
    lastUpdated: relativeDate(20),
    createdAt: relativeDate(42),
    timeline: [
      { id: 't31', applicationId: 'shopify-001', status: 'Applied', notes: 'Applied online.', createdAt: relativeDate(42) },
      { id: 't32', applicationId: 'shopify-001', status: 'Recruiter Screen', notes: 'Recruiter chat. Spoke about Ruby/TypeScript experience.', createdAt: relativeDate(34) },
      { id: 't33', applicationId: 'shopify-001', status: 'Ghosted', notes: 'No responses to multiple follow-ups over 4 weeks.', createdAt: relativeDate(20) },
    ]
  },
  {
    id: 'intercom-001',
    company: 'Intercom',
    position: 'Senior Product Engineer (AI Agents)',
    status: 'Saved',
    location: 'Dublin, IE',
    remote: 'Hybrid',
    salaryMin: 140000,
    salaryMax: 180000,
    salaryText: '€120,000 - €150,000',
    source: 'BuiltIn',
    jobUrl: 'https://intercom.com/careers',
    notes: 'Extremely interesting role building Fin AI agents. Saved this job, brushing up my resume to tailor it for AI customer support applications.',
    appliedDate: undefined,
    lastUpdated: relativeDate(1),
    createdAt: relativeDate(1),
    timeline: [
      { id: 't34', applicationId: 'intercom-001', status: 'Saved', notes: 'Found posting and saved it.', createdAt: relativeDate(1) },
    ]
  },
  {
    id: 'netflix-001',
    company: 'Netflix',
    position: 'Senior UI Engineer (Core UI)',
    status: 'Withdrawn',
    location: 'Los Gatos, CA',
    remote: 'Hybrid',
    salaryMin: 250000,
    salaryMax: 600000,
    salaryText: '$350,000 - $550,000 All-Cash',
    source: 'LinkedIn',
    jobUrl: 'https://netflix.com/careers',
    notes: 'Withdrew because they require 4 days a week onsite in Los Gatos, and I cannot relocate at this time since Microsoft offer is hybrid in Seattle/Redmond.',
    appliedDate: relativeDate(35),
    lastUpdated: relativeDate(24),
    createdAt: relativeDate(35),
    timeline: [
      { id: 't35', applicationId: 'netflix-001', status: 'Applied', notes: 'Applied via employee referral.', createdAt: relativeDate(35) },
      { id: 't36', applicationId: 'netflix-001', status: 'Recruiter Screen', notes: 'Recruiter discussion on comp and location details.', createdAt: relativeDate(28) },
      { id: 't37', applicationId: 'netflix-001', status: 'Withdrawn', notes: 'Withdrew due to strict relocation guidelines.', createdAt: relativeDate(24) },
    ]
  },
  {
    id: 'airbnb-001',
    company: 'Airbnb',
    position: 'Senior Frontend Engineer (Guest Experience)',
    status: 'Applied',
    location: 'San Francisco, CA',
    remote: 'Remote',
    salaryMin: 175000,
    salaryMax: 220000,
    salaryText: '$180,000 - $215,000',
    source: 'LinkedIn',
    jobUrl: 'https://airbnb.com/careers',
    notes: 'Applied last night. Airbnb has a great remote policy ("live and work anywhere"). Fingers crossed.',
    appliedDate: relativeDate(1),
    lastUpdated: relativeDate(1),
    createdAt: relativeDate(1),
    timeline: [
      { id: 't38', applicationId: 'airbnb-001', status: 'Applied', notes: 'Applied via company job board.', createdAt: relativeDate(1) },
    ]
  },
  {
    id: 'linear-001',
    company: 'Linear',
    position: 'Product Engineer',
    status: 'Recruiter Screen',
    location: 'Remote (US/EU)',
    remote: 'Remote',
    salaryMin: 150000,
    salaryMax: 210000,
    salaryText: '$150,000 - $210,000 + Equity',
    source: 'Linear Careers',
    jobUrl: 'https://linear.app/careers',
    notes: 'Received an email from a designer/engineer for an initial culture alignment call next Friday. Linear is my dream company!',
    appliedDate: relativeDate(8),
    lastUpdated: relativeDate(3),
    createdAt: relativeDate(8),
    timeline: [
      { id: 't39', applicationId: 'linear-001', status: 'Applied', notes: 'Submitted tailored application showcasing custom project work.', createdAt: relativeDate(8) },
      { id: 't40', applicationId: 'linear-001', status: 'Recruiter Screen', notes: 'Received invite for screening call.', createdAt: relativeDate(3) },
    ]
  },
  {
    id: 'vercel-001',
    company: 'Vercel',
    position: 'Developer Advocate (Next.js)',
    status: 'Applied',
    location: 'Remote',
    remote: 'Remote',
    salaryMin: 140000,
    salaryMax: 190000,
    salaryText: '$140,000 - $190,000',
    source: 'Twitter/X',
    jobUrl: 'https://vercel.com/careers',
    notes: 'Submitted a short loom video alongside my application. Fingers crossed that it stands out!',
    appliedDate: relativeDate(4),
    lastUpdated: relativeDate(4),
    createdAt: relativeDate(4),
    timeline: [
      { id: 't41', applicationId: 'vercel-001', status: 'Applied', notes: 'Applied with custom Loom video link.', createdAt: relativeDate(4) },
    ]
  },
  {
    id: 'notion-001',
    company: 'Notion',
    position: 'Full-Stack Engineer (Workspace)',
    status: 'Interview',
    location: 'San Francisco, CA',
    remote: 'Hybrid',
    salaryMin: 160000,
    salaryMax: 210000,
    salaryText: '$160,000 - $210,000',
    source: 'Indeed',
    jobUrl: 'https://notion.so/careers',
    notes: 'Finished the recruiter round. Had a coding assessment last week. Just scheduled a live design review round with the product team.',
    appliedDate: relativeDate(15),
    lastUpdated: relativeDate(2),
    createdAt: relativeDate(15),
    timeline: [
      { id: 't42', applicationId: 'notion-001', status: 'Applied', notes: 'Applied via job board.', createdAt: relativeDate(15) },
      { id: 't43', applicationId: 'notion-001', status: 'Recruiter Screen', notes: 'Recruiter chat. Talked about passion for productive tools.', createdAt: relativeDate(11) },
      { id: 't44', applicationId: 'notion-001', status: 'Interview', notes: 'Scheduled live system and UI design session.', createdAt: relativeDate(2) },
    ]
  },
  {
    id: 'github-001',
    company: 'GitHub',
    position: 'Senior Engineer (Copilot Team)',
    status: 'Saved',
    location: 'Remote',
    remote: 'Remote',
    salaryMin: 150000,
    salaryMax: 230000,
    salaryText: '$150,000 - $230,000',
    source: 'LinkedIn',
    jobUrl: 'https://github.com/careers',
    notes: 'Job opened yesterday. Focusing on generative AI and IDE developer experiences. Planning to apply tonight.',
    appliedDate: undefined,
    lastUpdated: relativeDate(1),
    createdAt: relativeDate(1),
    timeline: [
      { id: 't45', applicationId: 'github-001', status: 'Saved', notes: 'Saved for later.', createdAt: relativeDate(1) },
    ]
  },
  {
    id: 'datadog-001',
    company: 'Datadog',
    position: 'Solutions Engineer',
    status: 'Ghosted',
    location: 'Boston, MA',
    remote: 'Hybrid',
    salaryMin: 110000,
    salaryMax: 150000,
    salaryText: '$120,000 + Bonus',
    source: 'Indeed',
    jobUrl: 'https://datadoghq.com',
    notes: 'Applied 2 months ago. Never heard a single word back. Standard ghosting behavior.',
    appliedDate: relativeDate(60),
    lastUpdated: relativeDate(45),
    createdAt: relativeDate(60),
    timeline: [
      { id: 't46', applicationId: 'datadog-001', status: 'Applied', notes: 'Applied through Indeed.', createdAt: relativeDate(60) },
      { id: 't47', applicationId: 'datadog-001', status: 'Ghosted', notes: 'No response after 45 days.', createdAt: relativeDate(45) },
    ]
  },
  {
    id: 'figma-001',
    company: 'Figma',
    position: 'UI Engineer (Editor Frameworks)',
    status: 'Recruiter Screen',
    location: 'San Francisco, CA',
    remote: 'Hybrid',
    salaryMin: 180000,
    salaryMax: 240000,
    salaryText: '$180,000 - $240,000 + Stock',
    source: 'LinkedIn',
    jobUrl: 'https://figma.com/careers',
    notes: 'Recruiter reached out via LinkedIn. Scheduled introductory call for tomorrow.',
    appliedDate: relativeDate(3),
    lastUpdated: relativeDate(2),
    createdAt: relativeDate(3),
    timeline: [
      { id: 't48', applicationId: 'figma-001', status: 'Applied', notes: 'Recruiter reach-out response on LinkedIn.', createdAt: relativeDate(3) },
      { id: 't49', applicationId: 'figma-001', status: 'Recruiter Screen', notes: 'Scheduling recruiter introduction.', createdAt: relativeDate(2) },
    ]
  },
  {
    id: 'slack-001',
    company: 'Slack',
    position: 'Staff Frontend Engineer (Desktop)',
    status: 'Rejected',
    location: 'San Francisco, CA',
    remote: 'Hybrid',
    salaryMin: 185000,
    salaryMax: 240000,
    salaryText: '$190,000 - $235,000',
    source: 'Salesforce Careers',
    jobUrl: 'https://slack.com/careers',
    notes: 'Failed the initial live coding screen. It was heavily algorithm-focused (hard dynamic programming) and I tripped up on edge cases.',
    appliedDate: relativeDate(38),
    lastUpdated: relativeDate(30),
    createdAt: relativeDate(38),
    timeline: [
      { id: 't50', applicationId: 'slack-001', status: 'Applied', notes: 'Applied via Salesforce career portal.', createdAt: relativeDate(38) },
      { id: 't51', applicationId: 'slack-001', status: 'Assessment', notes: 'Coding exercise scheduled.', createdAt: relativeDate(34) },
      { id: 't52', applicationId: 'slack-001', status: 'Rejected', notes: 'Rejection letter received after technical evaluation.', createdAt: relativeDate(30) },
    ]
  },
  {
    id: 'discord-001',
    company: 'Discord',
    position: 'Senior Frontend Engineer (Voice & Video)',
    status: 'Assessment',
    location: 'San Francisco, CA',
    remote: 'Hybrid',
    salaryMin: 165000,
    salaryMax: 210000,
    salaryText: '$165,000 - $210,000',
    source: 'BuiltIn',
    jobUrl: 'https://discord.com/careers',
    notes: 'Received a Byteboard tech assessment invitation. Must complete it within 7 days.',
    appliedDate: relativeDate(5),
    lastUpdated: relativeDate(4),
    createdAt: relativeDate(5),
    timeline: [
      { id: 't53', applicationId: 'discord-001', status: 'Applied', notes: 'Applied on Discord board.', createdAt: relativeDate(5) },
      { id: 't54', applicationId: 'discord-001', status: 'Assessment', notes: 'Byteboard assessment invitation.', createdAt: relativeDate(4) },
    ]
  },
  {
    id: 'canva-001',
    company: 'Canva',
    position: 'Front End Engineer (UI Engine)',
    status: 'Applied',
    location: 'Austin, TX',
    remote: 'Hybrid',
    salaryMin: 140000,
    salaryMax: 180000,
    salaryText: '$140,000 - $180,000',
    source: 'LinkedIn',
    jobUrl: 'https://canva.com/careers',
    notes: 'Applied with referral from college alumni. Hoping to get a recruiter screening soon.',
    appliedDate: relativeDate(9),
    lastUpdated: relativeDate(9),
    createdAt: relativeDate(9),
    timeline: [
      { id: 't55', applicationId: 'canva-001', status: 'Applied', notes: 'Applied using college referral.', createdAt: relativeDate(9) },
    ]
  },
  {
    id: 'replit-001',
    company: 'Replit',
    position: 'Software Engineer (Compiler Tools)',
    status: 'Saved',
    location: 'San Francisco, CA',
    remote: 'Onsite',
    salaryMin: 150000,
    salaryMax: 220000,
    salaryText: '$150,000 - $220,000 + Equity',
    source: 'Twitter/X',
    jobUrl: 'https://replit.com/careers',
    notes: 'Amjad posted about a role building fast compilation layers. This would be incredibly educational.',
    appliedDate: undefined,
    lastUpdated: relativeDate(14),
    createdAt: relativeDate(14),
    timeline: [
      { id: 't56', applicationId: 'replit-001', status: 'Saved', notes: 'Saved Amjad\'s X post for application review.', createdAt: relativeDate(14) },
    ]
  },
  {
    id: 'hashicorp-001',
    company: 'HashiCorp',
    position: 'Software Engineer (Terraform)',
    status: 'Withdrawn',
    location: 'Remote',
    remote: 'Remote',
    salaryMin: 140000,
    salaryMax: 195000,
    salaryText: '$145,000 - $185,000',
    source: 'Indeed',
    jobUrl: 'https://hashicorp.com/careers',
    notes: 'Withdrew application early on because I received Microsoft\'s offer and preferred their team roadmap and Azure scaling over current HashiCorp status.',
    appliedDate: relativeDate(45),
    lastUpdated: relativeDate(28),
    createdAt: relativeDate(45),
    timeline: [
      { id: 't57', applicationId: 'hashicorp-001', status: 'Applied', notes: 'Applied via Indeed.', createdAt: relativeDate(45) },
      { id: 't58', applicationId: 'hashicorp-001', status: 'Recruiter Screen', notes: 'Recruiter screen scheduled.', createdAt: relativeDate(35) },
      { id: 't59', applicationId: 'hashicorp-001', status: 'Withdrawn', notes: 'Sent withdrawal note as other options advanced.', createdAt: relativeDate(28) },
    ]
  },
  {
    id: 'asana-001',
    company: 'Asana',
    position: 'Product Engineer',
    status: 'Ghosted',
    location: 'San Francisco, CA',
    remote: 'Hybrid',
    salaryMin: 150000,
    salaryMax: 200000,
    salaryText: '$150,000 - $200,000',
    source: 'LinkedIn',
    jobUrl: 'https://asana.com/careers',
    notes: 'Applied 8 weeks ago. No email, no rejection, just complete silence.',
    appliedDate: relativeDate(56),
    lastUpdated: relativeDate(40),
    createdAt: relativeDate(56),
    timeline: [
      { id: 't60', applicationId: 'asana-001', status: 'Applied', notes: 'Applied online via LinkedIn.', createdAt: relativeDate(56) },
      { id: 't61', applicationId: 'asana-001', status: 'Ghosted', notes: 'Marked as ghosted after 40 days of silence.', createdAt: relativeDate(40) },
    ]
  },
  {
    id: 'dropbox-001',
    company: 'Dropbox',
    position: 'Senior UI Developer',
    status: 'Rejected',
    location: 'Remote (US)',
    remote: 'Remote',
    salaryMin: 150000,
    salaryMax: 205000,
    salaryText: '$155,000 - $195,000',
    source: 'BuiltIn',
    jobUrl: 'https://dropbox.com/jobs',
    notes: 'Recruiter screening was highly technical but they rejected me saying they decided to prioritize candidates with specialized native desktop client integration experience.',
    appliedDate: relativeDate(25),
    lastUpdated: relativeDate(20),
    createdAt: relativeDate(25),
    timeline: [
      { id: 't62', applicationId: 'dropbox-001', status: 'Applied', notes: 'Applied via BuiltIn platform.', createdAt: relativeDate(25) },
      { id: 't63', applicationId: 'dropbox-001', status: 'Recruiter Screen', notes: 'Detailed recruiter conversation about platform UI layers.', createdAt: relativeDate(22) },
      { id: 't64', applicationId: 'dropbox-001', status: 'Rejected', notes: 'Rejection notice received.', createdAt: relativeDate(20) },
    ]
  }
];
